title: Marca e Deixa
description: Manual do usuário
theme: minima

# Informações pessoais (opcional)
author:
  name: Carolina Peçaibes
  email: seuemail@example.com

# Configurações opcionais
markdown: kramdown
highlighter: rouge
